services:
  gmb_app:
    build:
      context: .
    container_name: gmb_app
    platform: linux/amd64
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www
    depends_on:
      - gmb_db
    ports:
      - "8088:80"
    networks:
      - gmb_network

  gmb_db:
    image: mysql:8.0
    container_name: gmb_db
    hostname: gmb_db
    platform: linux/amd64
    volumes:
      - gmb_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "deployer"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "gmb_app"
      MYSQL_USER: "gmb_db_user"
      MYSQL_PASSWORD: "deployer"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_TCP_PORT: 33061
    ports:
      - "33061:3306"
    networks:
      - gmb_network

  gmb_cache:
    image: memcached:latest
    container_name: gmb_cache
    hostname: gmb_cache
    platform: linux/amd64
    restart: always
    ports:
      - "11222:11211"
    networks:
      - gmb_network

volumes:
  gmb_db:
    driver: local

networks:
  gmb_network:
    driver: bridge
